Дз 11
tdvsz/javascript-basic-course pull request #8
Opened 2024-03-09 19:23 UTC by tdvsz

2024-03-10 14:19 UTC, GitEsense requested changes
Надеюсь вопросов не возникнет более)

2024-03-10 14:19 UTC, GitEsense commented on 11-date-array/date_array.js
> +  console.log(filteredArr);
Данная задача решается при помощи предыдущего алгоритма (как раз Вы уже проходили filter функцию после прошлого ДЗ.
Порядок задачи следующий:
1. Вы получаете массив строк
2. Проходите каждый элемент (строку) и разбиваете на шаблон (массив из 3 элементов - ДД, ММ, ГГГГ
3. Фильтруем результирующий массив через filter, передав туда patter валидации полученных дат
4. Выводим результат (все валидные массивы собираем через join("-")

Пример
```js
const dateString =  "10-02-2022"
const arrStr = dateString.split("-")   // ["10", "02", "2022"]
isValidDate(arrStr)   // true
arrStr.join("-")


const dateString =  "10-22-2022"
const arrStr = dateString.split("-")   // ["10", "22", "2022"]
isValidDate(arrStr)   // false
```

Вы проверяете на один шаблон, если не соответствует, тогда на второй шаблон, если подходит - проходим дальше и смотрим "валидна ли дата", если да - мы получаем "true" и значит фильтру соответствует, значит будет возвращено

Пример вызова
```js
filterDateArray(array, filterPattern){
   // Тут происходит магия
   return array
}

isValidDate(params (массив или строка - на Ваше усмотрение)){
   // Тут проверяем дату и возвращаем булево (валидно или нет)
   // Проверка смотрит "существует ли такая дата, проверяет високосный год и т.п.)
}

const stringArray = [
  "10-02-2022",
  "тест",
  "11/12/2023",
  "00/13/2022",
  "41/12/2023",
  "02/29/2023",
  "02/29/2024",
  "tt/11/20ts",
  "012/011/20ts",
];
const resultArray = filterDateArray(stringArray , isValidDate)
console.log(resultArray)   //   [ '10-02-2022', '12-11-2023', '29-02-2024' ]
```

2024-03-14 20:18 UTC, tdvsz commented on 11-date-array/date_array.js
> +  console.log(filteredArr);
Тут более-менее вопросов нет, если дата имеет вид: дд, мм, гггг. Не понятно, что делать с датами мм, дд, гггг

2024-03-21 07:20 UTC, GitEsense approved these changes
В целом всё отлично, решение хорошее, но логика чуток уступает, так же лучше стараться не использовать дорогие операции, можно было сделать что-то "читабельное" и "удобное" вроде такой реализации
```js
const stringArray = [
  '10-02-2022',
  'тест',
  '31-01-2023',
  '11/12/2023',
  '00/13/2022',
  '41/12/2023',
  '02/29/2023',
  '02/29/2024',
  'tt/11/20ts',
  '012/011/20ts',
  '29-07-2024'
];

function getDates(array, fn) {
    const resultArr = [...array];
    return resultArr
        .map(stringToArray)
        .filter(fn)
        .map((array) => array.join('-'));
}

function stringToArray(dateString) {
    let [day, month, year] = dateString.split('-');
    if (!year) {
        [month, day, year] = dateString.split('/');
    }
    if (!year || isNaN(day) || isNaN(month) || isNaN(year)) {
        return null;
    }

    return [day, month, year];
}

function checkCorrectDate(array) {
    if (array === null) {
        return false;
    }

    const LONG_MONTH_ARRAY = [1, 3, 5, 7, 8, 10, 12];

    const [day, month, year] = array.map(Number);

    const isLeapYear = (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;

    // check month
    if (month > 12 || month < 1) {
        return false;
    }

    // check day
    if (day > 31 || day < 1) {
        return false;
    }

    if (day === 31 && !LONG_MONTH_ARRAY.includes(month)) {
        return false;
    }

    // check February for correct day and leap year
    if (month === 2) {
        if (day === 30 || (day === 29 && !isLeapYear)) {
            return false;
        }
    }

    return true;
}

console.log(getDates(stringArray, checkCorrectDate));
```

2024-03-21 07:20 UTC, GitEsense commented on 11-date-array/date_array.js
> +  if ((day > 0 && day < 31) && (month > 0 && month < 12) && (year > 1000 && year < 9999)) return true;
Всё бы ничего, только вот если передать 31 января (любого года), то он не пройдёт парсинг, т.к. у нас по условию < 31, так же не понятно "где надо смотреть 30 дней, а где 31"

2024-03-21 07:20 UTC, GitEsense commented on 11-date-array/date_array.js
> +        parts.unshift(day);
Использовать методы **shift**, **unshift**, **splice** - это всегда очень дорого. Нужно стараться их избегать по возможности. Это связано с перестроением указателей в массивах, поэтому если есть возможность не использовать, лучше не использовать.

2024-03-21 17:30 UTC, merged